### ISSUE TITLE
Images are automatically loaded

### ISSUE THREAD

**Issue by johnwmcarneiro** [rilwis/meta-box#847] opened 2016-04-25 17:34 UTC
Hello,
I am using the metabox to upload multiple images. When I click to new post, it automatically is using the images of the 'Media' no I have chosen.
Every new post it loads all images of 'Media'.
Have any setting should I do so that it does not automatically load the images?
`add_filter( 'rwmb_meta_boxes', 'sizy_post_metaboxes' );
function sizy_post_metaboxes( $meta_boxes ) {
  global $text_domain;
  $prefix = 'sz_post_';
  $meta_boxes[] = array(
    'title'  => __( 'Informações', $text_domain ),
    'post_types'  => 'post',
    'priority' => 'high',
    'fields' => array(
      array(
        'id' => $prefix . 'local',
        'type' => 'text',
        'name' => __( 'Local do evento', $text_domain )
      ),
      array(
        'id' => $prefix . 'photo',
        'name' => __( 'Imagens', $text_domain ),
        'type' => 'image_upload',
        'force_delete'     => false
      ),
    )
  );
  return $meta_boxes;
}`

**Comment by johnwmcarneiro** [comment] 2016-04-25 19:15
Hello,
In PHP 5.6 is giving problems, set up to version 5.5 and it worked normally.
But I found the problem, the plugin makes a query_attachments request to admin-ajax.php informing the draft ID instead of Wordpress return empty it returns all images. I checked the file wp-admin / includes / ajax-actions.php on line 2363 "$query = array_intersect_key ($query, array_flip ($keys))", PHP 5.6 does not include the post__in for some reason, and just returning all images.
I do not know if it's correct, but I think it could verify that it is indeed necessary to request the images when the post is still in draft.

**Comment by funkedgeek** [comment] 2016-04-25 20:33
What version of the plugin are you using?

**Comment by johnwmcarneiro** [comment] 2016-04-25 20:36
I'm using the latest 4.8.5.

**Comment by funkedgeek** [comment] 2016-04-26 23:11
That query is just the image modal getting all the images.  Not sure what is going on.  What plugins do you have active?

**Comment by johnwmcarneiro** [comment] 2016-04-26 23:31
So as I said, I decided when I changed PHP's version from 5.6 to 5.5, what I realized is that the request was not being sent with the variable post__in, I will install a new site on my server to try to test again and demonstrate the problem, because the site that I fix is in production.

**Comment by edcousins** [comment] 2016-05-02 00:00
Did you find a fix for this @johnwmcarneiro ? We have a user with the same issue, but unable to replicate in any local instances, and no other users seem to have the issue. Very strange!

**Comment by johnwmcarneiro** [comment] 2016-05-02 00:28
To fix I did downgrade the PHP from 5.6 to 5.5.
The problem is in function array_intersect_key in wp-admin/includes/ajax-actions.php on line 2363 "$query = array_intersect_key ($query, array_flip ($keys));".
In PHP5.6 it works one way and not another PHP5.5, in PHP5.6 it does not include the post__IN variable.
I can not fix the code, sorry.

**Comment by funkedgeek** [comment] 2016-05-02 06:54
wierd because I have PHP 5.6 and it doesn't do this

**Comment by funkedgeek** [comment] 2016-05-13 12:06
Has this been fixed for you?  I recently edited some code that should resolve this

**Comment by edcousins** [comment] 2016-05-13 12:39
Hi @funkedgeek 

We've only had one user with the issue, as of yet, haven't found a fix.

**Comment by funkedgeek** [comment] 2016-05-13 12:56
Have you tried the latest version of the plugin on GitHub?

**Comment by edcousins** [comment] 2016-05-13 13:06
No - but will do. Unfortunately the user with the issue is no longer using the theme, so will have to look out for any re-occurence. Thanks for letting me know.

**Closed** 2016-05-14 01:38 UTC

**Comment by edcousins** [comment] 2016-05-19 19:13
Just to let you know, latest update fixed the issue - thanks.
