### ISSUE TITLE
slider + text box field type

### ISSUE THREAD

**Issue by dazzlesoftware** [rilwis/meta-box#392] opened 2013-12-20 06:29 UTC
Hello is it possible to create slider and textbox that clones as I have this working using my theme framework but trying to do the same with meta-box as its reviews system that you input the name and score for example graphics as text and slider to 70% and you clone to add more as I tried the group but does not create same effect as need them group together not having the boxes separate that clones

Stephen

**Comment by funkedgeek** [comment] 2015-10-21 02:37
Duplicate of https://github.com/rilwis/meta-box/issues/394

**Closed by funkedgeek** 2015-10-21 02:37 UTC
