### ISSUE TITLE
create more then one field type with clone feature

### ISSUE THREAD

**Issue by dazzlesoftware** [rilwis/meta-box#387] opened 2013-12-09 04:34 UTC
Hello I been trying to create an text box and slider with clone but not having any luck I tried creating my own meta class but don't seem to have any luck is this even possible as was trying to develop small plugin of my own based on yours for content and reviews 
as I need textbox and slider that I can clone.

Stephen

**Comment by funkedgeek** [comment] 2015-10-21 02:37
Duplicate of https://github.com/rilwis/meta-box/issues/394

**Closed by funkedgeek** 2015-10-21 02:37 UTC
