### ISSUE TITLE
4.8.0 update error when using with Meta Box Group

### ISSUE THREAD

**Issue by yoroshiku24** [rilwis/meta-box#769] opened 2016-02-17 15:30 UTC
I use Meta Box with Meta Box Group extension. When I updated Meta Box to 4.8.0, I get this error:
`Warning: call_user_func() expects parameter 1 to be a valid callback, class 'RWMB_Group_Field' not found in D:\xampp\htdocs\wordpress\wp-content\plugins\meta-box\inc\meta-box.php on line 353`

It had happened before, but the last time I updated Meta Box Group to the latest available update (1.0.4) and it worked again. But this time, I haven't seen a new version of Meta Box Group. I purchased the Meta Box Group to use in my theme, and it's very frustrating for me and my clients if every time Meta Box gets a new update, I will get a problem with the Meta Box Group plugin.

Hope you will fix this issue soon.

Best,

**Comment by funkedgeek** [comment] 2016-02-17 15:32
4.8 updates how we load classes, so I'm assuming this is related to that.  We'll get working on a solution soon.

**Comment by ringmstr955** [comment] 2016-02-17 16:22
We are experiencing the same error mentioned by @yoroshiku24 as well. A quick update to the Meta Box Group Plugin would be very appreciative since we too have client projects that are impacted and need the fix asap.

**Comment by ryanlabelle** [comment] 2016-02-17 18:12
Experiencing the same issue, after upgrading to 4.8.

Before: http://new.tinygrab.com/6407caa59e5d54225e42221118aaba162e8420551f.png

After: http://new.tinygrab.com/6407caa59e1d50292986c9a10b6ab2bb6e325b81a5.png

Thanks for the urgent response, we are supporting thousands of installs. :)

**Comment by hanswembacher** [comment] 2016-02-17 21:58
have the same issue, updated 3 hours ago, then selecting groups is no longer saved when saving, so it shows all content without filtering/selection. hope for a quick fix. thanks

**Comment by rilwis** [comment] 2016-02-18 07:48
Hi, I've just updated the Group extension and pushed fixes for Meta Box on Github. Can you please update the Group extension with **new code of Meta Box** on Github? We'll release a new version of Meta Box when that's confirmed to work.

**Comment by hanswembacher** [comment] 2016-02-18 08:28
works now, thanks a lot :-)

**Closed** 2016-02-18 09:53 UTC
